export const Raid_EternitySand = [
  {
    quest_id: '305321',
    level: '120',
    element: 'fire',
    tweet_name_en: 'Lvl 120 Atum',
    tweet_name_jp: 'Lv120 アトゥム',
    quest_name_en: 'Atum (Impossible)',
    quest_name_jp: 'アトゥムＨＬ',
    impossible: 2,
    difficulty: '2',
    stage_id: '12022',
    thumbnail_image: 'high_ennead_03',
    is_blue_treasure: true,
  },
  {
    quest_id: '305331',
    level: '120',
    element: 'water',
    tweet_name_en: 'Lvl 120 Tefnut',
    tweet_name_jp: 'Lv120 テフヌト',
    quest_name_en: 'Tefnut (Impossible)',
    quest_name_jp: 'テフヌトＨＬ',
    impossible: 2,
    difficulty: '2',
    stage_id: '12022',
    thumbnail_image: 'high_ennead_03',
    is_blue_treasure: true,
  },
  {
    quest_id: '305341',
    level: '120',
    element: 'earth',
    tweet_name_en: 'Lvl 120 Bennu',
    tweet_name_jp: 'Lv120 ベンヌ',
    quest_name_en: 'Bennu (Impossible)',
    quest_name_jp: 'ベンヌＨＬ',
    impossible: 2,
    difficulty: '2',
    stage_id: '12022',
    thumbnail_image: 'high_ennead_03',
    is_blue_treasure: true,
  },
  {
    quest_id: '305351',
    level: '120',
    element: 'wind',
    tweet_name_en: 'Lvl 120 Ra',
    tweet_name_jp: 'Lv120 ラー',
    quest_name_en: 'Ra (Impossible)',
    quest_name_jp: 'ラーＨＬ',
    impossible: 2,
    difficulty: '2',
    stage_id: '12022',
    thumbnail_image: 'high_ennead_03',
    is_blue_treasure: true,
  },
  {
    quest_id: '305361',
    level: '120',
    element: 'light',
    tweet_name_en: 'Lvl 120 Horus',
    tweet_name_jp: 'Lv120 ホルス',
    quest_name_en: 'Horus (Impossible)',
    quest_name_jp: 'ホルスＨＬ',
    impossible: 2,
    difficulty: '2',
    stage_id: '12022',
    thumbnail_image: 'high_ennead_03',
    is_blue_treasure: true,
  },
  {
    quest_id: '305371',
    level: '120',
    element: 'dark',
    tweet_name_en: 'Lvl 120 Osiris',
    tweet_name_jp: 'Lv120 オシリス',
    quest_name_en: 'Osiris (Impossible)',
    quest_name_jp: 'オシリスＨＬ',
    impossible: 2,
    difficulty: '2',
    stage_id: '12022',
    thumbnail_image: 'high_ennead_03',
    is_blue_treasure: true,
  },
  {
    quest_id: '303241',
    level: '120',
    element: 'wind',
    tweet_name_en: 'Lvl 150 Tiamat Malice',
    tweet_name_jp: 'Lv150 ティアマト・マリス',
    quest_name_en: 'Tiamat Malice (Impossible)',
    quest_name_jp: 'ティアマト・マリスＨＬ',
    impossible: 2,
    difficulty: '3',
    stage_id: '12031',
    thumbnail_image: 'high_malice',
    is_blue_treasure: false,
  },
  {
    quest_id: '305151',
    level: '120',
    element: 'water',
    tweet_name_en: 'Lvl 150 Leviathan Malice',
    tweet_name_jp: 'Lv150 リヴァイアサン・マリス',
    quest_name_en: 'Leviathan Malice (Impossible)',
    quest_name_jp: ' リヴァイアサン・マリスＨＬ',
    impossible: 2,
    difficulty: '3',
    stage_id: '12031',
    thumbnail_image: 'high_malice',
    is_blue_treasure: false,
  },
  {
    quest_id: '305251',
    level: '120',
    element: 'earth',
    tweet_name_en: 'Lvl 150 Phronesis',
    tweet_name_jp: 'Lv150 フロネシス',
    quest_name_en: 'Phronesis (Impossible)',
    quest_name_jp: 'フロネシスＨＬ',
    impossible: 2,
    difficulty: '3',
    stage_id: '12031',
    thumbnail_image: 'high_malice',
    is_blue_treasure: false,
  },
  {
    quest_id: '305271',
    level: '120',
    element: 'light',
    tweet_name_en: 'Lvl 150 Luminiera Malice',
    tweet_name_jp: 'Lv150 シュヴァリエ・マリス',
    quest_name_en: 'Luminiera Malice (Impossible)',
    quest_name_jp: 'シュヴァリエ・マリスＨＬ',
    impossible: 2,
    difficulty: '3',
    stage_id: '12031',
    thumbnail_image: 'high_malice',
    is_blue_treasure: false,
  },
  {
    quest_id: '305291',
    level: '120',
    element: 'dark',
    tweet_name_en: 'Lvl 150 Anima-Animus Core',
    tweet_name_jp: 'Lv150 アニマ・アニムス・コア',
    quest_name_en: 'Anima-Animus Core (Impossible)',
    quest_name_jp: 'アニマ・アニムス・コアＨＬ',
    impossible: 2,
    difficulty: '3',
    stage_id: '12031',
    thumbnail_image: 'high_malice',
    is_blue_treasure: false,
  },
  {
    quest_id: '305481',
    level: '120',
    element: 'fire',
    tweet_name_en: 'Lvl 150 Legion Void',
    tweet_name_jp: 'Lv150 レギオン・ヴォイド',
    quest_name_en: 'Legion Void (Impossible)',
    quest_name_jp: 'レギオン・ヴォイドＨＬ',
    impossible: 2,
    difficulty: '3',
    stage_id: '12031',
    thumbnail_image: 'high_malice',
    is_blue_treasure: false,
  },
  {
    quest_id: '305381',
    level: '200',
    element: 'fire',
    tweet_name_en: 'Lvl 275 Mugen',
    tweet_name_jp: 'Lv275 ムゲン',
    quest_name_en: 'Mugen (Impossible)',
    quest_name_jp: 'ムゲンＨＬ',
    impossible: 2,
    difficulty: '8',
    stage_id: '12081',
    thumbnail_image: 'high_diaspora_2',
    is_blue_treasure: true,
  },
  {
    quest_id: '305391',
    level: '200',
    element: 'water',
    tweet_name_en: 'Lvl 275 Diaspora',
    tweet_name_jp: 'Lv275 ディアスポラ',
    quest_name_en: 'Diaspora (Impossible)',
    quest_name_jp: 'ディアスポラＨＬ',
    impossible: 2,
    difficulty: '8',
    stage_id: '12081',
    thumbnail_image: 'high_diaspora_2',
    is_blue_treasure: true,
  },
  {
    quest_id: '305401',
    level: '200',
    element: 'earth',
    tweet_name_en: 'Lvl 275 Siegfried',
    tweet_name_jp: 'Lv275 ジークフリート',
    quest_name_en: 'Siegfried (Impossible)',
    quest_name_jp: 'ジークフリートＨＬ',
    impossible: 2,
    difficulty: '8',
    stage_id: '12081',
    thumbnail_image: 'high_diaspora_2',
    is_blue_treasure: true,
  },
  {
    quest_id: '305411',
    level: '200',
    element: 'wind',
    tweet_name_en: 'Lvl 275 Seofon',
    tweet_name_jp: 'Lv275 シエテ',
    quest_name_en: 'Seofon (Impossible)',
    quest_name_jp: 'シエテＨＬ',
    impossible: 2,
    difficulty: '8',
    stage_id: '12081',
    thumbnail_image: 'high_diaspora_2',
    is_blue_treasure: true,
  },
  {
    quest_id: '305421',
    level: '200',
    element: 'light',
    tweet_name_en: 'Lvl 275 Cosmos',
    tweet_name_jp: 'Lv275 コスモス',
    quest_name_en: 'Cosmos (Impossible)',
    quest_name_jp: 'コスモスＨＬ',
    impossible: 2,
    difficulty: '8',
    stage_id: '12081',
    thumbnail_image: 'high_diaspora_2',
    is_blue_treasure: true,
  },
  {
    quest_id: '305431',
    level: '200',
    element: 'dark',
    tweet_name_en: 'Lvl 275 Agastia',
    tweet_name_jp: 'Lv275 アガスティア',
    quest_name_en: 'Agastia (Impossible)',
    quest_name_jp: 'アガスティアＨＬ',
    impossible: 2,
    difficulty: '8',
    stage_id: '12081',
    thumbnail_image: 'high_diaspora_2',
    is_blue_treasure: true,
  },
  {
    quest_id: '305311',
    level: '200',
    element: 'normal',
    tweet_name_en: 'Lvl 300 Super Ultimate Bahamut',
    tweet_name_jp: 'Lv300 スーパーアルティメットバハムート',
    quest_name_en: 'Rage of Super Ultimate Bahamut',
    quest_name_jp: '神撃せし蒼き究極の竜',
    impossible: 2,
    difficulty: '8',
    stage_id: '12082',
    thumbnail_image: 'high_ultimate_bahamut',
    is_blue_treasure: false,
  },
]
export const Raid_GoldBrick = [
  {
    quest_id: '301061',
    raidName: 'tuyobaha',
    level: '101',
    element: 'dark',
    tweet_name_en: 'Lvl 150 Proto Bahamut',
    tweet_name_jp: 'Lv150 プロトバハムート',
    quest_name_en: 'Wings of Terror (Impossible)',
    quest_name_jp: '邂逅、黒銀の翼ＨＬ',
    impossible: 2,
    difficulty: '6',
    stage_id: '12061',
    thumbnail_image: 'high_proto_bahamut',
    is_blue_treasure: true,
  },
  {
    quest_id: '303251',
    raidName: 'akx',
    level: '150',
    element: 'light',
    tweet_name_en: 'Lvl 200 Akasha',
    tweet_name_jp: 'Lv200 アーカーシャ',
    quest_name_en: 'Omen of the Broken Skies',
    quest_name_jp: '崩天、虚空の兆',
    impossible: 2,
    difficulty: '6',
    stage_id: '12061',
    thumbnail_image: 'high_proto_bahamut',
    is_blue_treasure: true,
  },
  {
    quest_id: '305161',
    raidName: 'gurande',
    level: '150',
    element: 'normal',
    tweet_name_en: 'Lvl 200 Grand Order',
    tweet_name_jp: 'Lv200 ジ・オーダー・グランデ',
    quest_name_en: 'The Peacemaker\'s Wings (Impossible)',
    quest_name_jp: '降臨、調停の翼ＨＬ',
    impossible: 2,
    difficulty: '6',
    stage_id: '12061',
    thumbnail_image: 'high_proto_bahamut',
    is_blue_treasure: true,
  },
  {
    quest_id: '303141',
    raidName: 'cb',
    level: '130',
    element: 'normal',
    tweet_name_en: 'Lvl 200 Ultimate Bahamut',
    tweet_name_jp: 'Lv200 アルティメットバハムート',
    quest_name_en: 'Empyreal Ascension (Impossible)',
    quest_name_jp: '神撃、究極の竜ＨＬ',
    impossible: 2,
    difficulty: '6',
    stage_id: '12061',
    thumbnail_image: 'high_proto_bahamut',
    is_blue_treasure: false,
  },
]

export const targetRaid = [
  ...Raid_EternitySand,
  ...Raid_GoldBrick,
]
